### PR TITLE
use pg_identify_object instead of regproc for plrust.plrust_proc

### PR DESCRIPTION
**Pull request by JohnHVancouver**
regproc is not supported in pg_upgrade so use pg_identify_object to generate a unique identity for the function

Discussed using object identity in #122

### CODE REVIEW

**Comment by eeeebbbbrrrr** [comment]
I’ve already done this.

**Comment by eeeebbbbrrrr** [comment]
There's a branch for it here:  https://github.com/tcdi/plrust/compare/main...pg_identify_object

I have not made a PR yet because it needs to be rebased

**Comment by eeeebbbbrrrr** [comment]
@JohnHVancouver I'm closing this one in favor or #141 that I just put up.  It doesn't use SQL to get the identifier value, which seems fragile and slow.

**Comment by JohnHVancouver** [comment]
Ah sorry didn't realize, thanks!

**Comment by eeeebbbbrrrr** [comment]
NP.  It was my bad for not even putting up the PR.  I'm juggling a lot of chainsaws...

**Pull request closed without merging**
