### PR TITLE
Turn us into a workspace

### PR DESCRIPTION
**Pull request by eeeebbbbrrrr**
This also upgrades plrust to pgx 0.6.0, from -alpha.1.

I think this does it, but it was too easy!  Lets see if CI does all the things it should **and** passes...

### CODE REVIEW

**Comment by workingjubilee** [comment]
> 2022-12-05T23:20:21.2027105Z error: could not find `Cargo.toml` in `/home/ec2-user/actions-runner/_work/plrust/plrust` or any parent directory

We need a Cargo.toml in the root of the workspace that handles the `[workspace]` bit, kinda like `pgx` has here:
https://github.com/tcdi/pgx/blob/e460d80d6aa8871d1b3d2c93d77595cbe09d487b/Cargo.toml#L1-L4

**Comment by eeeebbbbrrrr** [comment]
Would you believe I forgot to git add that?  Haha!

**Comment by eeeebbbbrrrr** [comment]
okay, lettuce see if this works...

**Comment by workingjubilee** [comment]
The tests will almost certainly fail but it should at least give us more interesting failures.

**Comment by eeeebbbbrrrr** [comment]
yah, I'm actually hoping for that.

Also, I wasn't sure what to do with the top-level `/build` script?  It doesn't even seem to "build" but instead "cargo test".  I suppose it should probably be moved into the new plrust crate subdirectory?

**Comment by eeeebbbbrrrr** [comment]
woah.  Might need to kick this over to your department?

https://github.com/tcdi/plrust/actions/runs/3625456059/jobs/6113523393#step:11:159

**Comment by eeeebbbbrrrr** [comment]
Lemme try a thing or two first... I need to better understand this stuff

**Comment by workingjubilee** [comment]
Yep, that one's "my fault".

**Comment by eeeebbbbrrrr** [comment]
Yeah, tag you're it @workingjubilee.  I don't know what to do about the errors that start here:  https://github.com/tcdi/plrust/actions/runs/3625533134/jobs/6113679321#step:11:159

Moving `/build` into `/plrust/` didn't make any difference.

Unless it has to do with build:27:

```shellscript
        git clone https://github.com/tcdi/postgrestd.git --branch "1.61" --recurse-submodules
```

Since this PR moves plrust's rust-toolchain to 1.65?

**Comment by workingjubilee** [comment]
Neat, the `postgrestd`-independent tests pass, so that part works.

**Review by workingjubilee — APPROVED** [review]
Cool, this works now!

**Pull request merged**
