### PR TITLE
Lint uses of `include_str`/`include_bytes`

### PR DESCRIPTION
**Pull request by thomcc**
This is probably required to avoid issues in cases where people `include_bytes!` things like keys and certificates.

### CODE REVIEW

**Comment by thomcc** [comment]
Surprised I managed to get all the cases. But it turns out we already had diagnostic items for these.

**Comment by eeeebbbbrrrr** [comment]
ha!  this is great!

**Review by workingjubilee — CHANGES_REQUESTED** [review]
I think you need to add a `#[should_panic]` to `postgrestd_no_include_str` or otherwise change the test.

**Review by workingjubilee — APPROVED** [review]
Thanks for taking care of that nit, Jubilee! :woman: :1st_place_medal: :woman:

**Comment by thomcc** [comment]
Thanks for taking care of that nit, Jubilee!

**Pull request merged**
