### PR TITLE
Upgrade to pgrx 0.9.7

### PR DESCRIPTION
**Pull request by workingjubilee**
A critical bug concerning handling arrays with an initial null element was discovered in pgrx versions 0.8.0 to 0.9.6, recommending an upgrade to 0.9.7 as soon as is possible.

### CODE REVIEW

**Review by eeeebbbbrrrr — APPROVED** [review]
This got all the places.  A++

**Comment by eeeebbbbrrrr** [comment]
Please target this to the `develop` branch

**Review by BradyBonnette — APPROVED** [review]
Nice :)

**Comment by BradyBonnette** [comment]
Oh looks like the tests are falling over. Might be the fact that Github just recently today had a hiccup. They probably need to be restarted.

**Comment by workingjubilee** [comment]
Writing a test to verify the PL/Rust fix is golden.

**Review by thomcc — APPROVED** [review]

**Pull request merged**
