### PR TITLE
 Declare postgres as vendor in tuples 

### PR DESCRIPTION
**Pull request by workingjubilee**
Let's see if this works.

### CODE REVIEW

**Comment by eeeebbbbrrrr** [comment]
please update `README.md` too once you've got things settled in.

**Comment by workingjubilee** [comment]
I haven't made it fully magical as most changes will get stomped by #155.

**Review by eeeebbbbrrrr — APPROVED** [review]
I’m happy when you and CI are

**Comment by thomcc** [comment]
See also #156 some of the motivation.

**Review by thomcc — APPROVED** [review]
It's very surprising to me that this can be done with a plrust patch (figured postrestd controlled its own target name), but great!

**Pull request merged**
