### PR TITLE
Test postgrestd/1.67.1

### PR DESCRIPTION
**Pull request by workingjubilee**

### CODE REVIEW

**Comment by thomcc** [comment]
I'm assuming we're doing this (and adjusting my code accordingly) but am not going to click merge just in case.

**Comment by eeeebbbbrrrr** [comment]
I don't think this is necessary now that #198 was merged?

**Comment by thomcc** [comment]
Ah, I should have merged this first probably (although that would have caused issues for you, since then I'd need to rebase). Sorry for the hassle my branch caused.

**Comment by workingjubilee** [comment]
It's nbd, honestly.

**Pull request closed without merging**
